/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all auctions */
    get: operations["GET__"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/checkouts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a Stripe Checkout session for a bid pack */
    post: operations["POST__api_v1_checkouts"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/checkout/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check the Stripe checkout session status */
    get: operations["GET__api_v1_checkout_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/checkout/success": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Handle successful checkout callbacks and credit the user */
    get: operations["GET__api_v1_checkout_success"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/bid_packs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List available bid packs */
    get: operations["GET__api_v1_bid_packs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auctions/{auction_id}/bids": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Place a bid on an auction */
    post: operations["POST__api_v1_auctions_{auction_id}_bids"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auctions/{auction_id}/bid_history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List bids for a given auction (newest first)
     * @description GET /api/v1/auctions/:auction_id/bid_history
     */
    get: operations["GET__api_v1_auctions_{auction_id}_bid_history"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auctions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all auctions */
    get: operations["GET__api_v1_auctions"];
    put?: never;
    /** Create a new auction (admin only) */
    post: operations["POST__api_v1_auctions"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auctions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a single auction with bids */
    get: operations["GET__api_v1_auctions_{id}"];
    /** Update an existing auction (admin only) */
    put: operations["PUT__api_v1_auctions_{id}"];
    post?: never;
    /** Retire an auction (admin only) */
    delete: operations["DELETE__api_v1_auctions_{id}"];
    options?: never;
    head?: never;
    /** Update an existing auction (admin only) */
    patch: operations["PATCH__api_v1_auctions_{id}"];
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register a new user account
     * @description POST /api/v1/users
     */
    post: operations["POST__api_v1_users"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log in and create a session
     * @description POST /api/v1/login
     */
    post: operations["POST__api_v1_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh the current session using a refresh token */
    post: operations["POST__api_v1_session_refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session/remaining": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return remaining time for the current session token */
    get: operations["GET__api_v1_session_remaining"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Log out and revoke the current session token
     * @description DELETE /api/v1/logout
     */
    delete: operations["DELETE__api_v1_logout"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/logged_in": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check whether the provided token is valid
     * @description GET /api/v1/logged_in
     */
    get: operations["GET__api_v1_logged_in"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/password/forgot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a password reset email */
    post: operations["POST__api_v1_password_forgot"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/password/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset a password using a token */
    post: operations["POST__api_v1_password_reset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/maintenance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Show public maintenance mode state
     * @description GET /api/v1/maintenance
     */
    get: operations["GET__api_v1_maintenance"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/maintenance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Show current maintenance mode state
     * @description GET /api/v1/admin/maintenance
     */
    get: operations["GET__api_v1_admin_maintenance"];
    put?: never;
    /**
     * Toggle maintenance mode on or off
     * @description POST /api/v1/admin/maintenance?enabled=true
     *     Also accepts JSON body { enabled: true }
     */
    post: operations["POST__api_v1_admin_maintenance"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/bid-packs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all bid packs (admin)
     * @description GET /admin/bid_packs
     */
    get: operations["GET__api_v1_admin_bid-packs"];
    put?: never;
    /**
     * Create
     * @description POST /admin/bid_packs
     */
    post: operations["POST__api_v1_admin_bid-packs"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/bid-packs/new": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Return a template bid pack for creation
     * @description GET /admin/bid_packs/new
     */
    get: operations["GET__api_v1_admin_bid-packs_new"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/bid-packs/{id}/edit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetch a bid pack for editing
     * @description GET /admin/bid_packs/:id/edit
     */
    get: operations["GET__api_v1_admin_bid-packs_{id}_edit"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/bid-packs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Show a bid pack (admin)
     * @description GET /admin/bid_packs/:id
     */
    get: operations["GET__api_v1_admin_bid-packs_{id}"];
    /**
     * Update a bid pack (admin)
     * @description PATCH/PUT /admin/bid_packs/:id
     */
    put: operations["PUT__api_v1_admin_bid-packs_{id}"];
    post?: never;
    /**
     * Retire (deactivate) a bid pack (admin)
     * @description DELETE /admin/bid_packs/:id
     *     Retires a bid pack to prevent purchase while keeping history.
     */
    delete: operations["DELETE__api_v1_admin_bid-packs_{id}"];
    options?: never;
    head?: never;
    /**
     * Update a bid pack (admin)
     * @description PATCH/PUT /admin/bid_packs/:id
     */
    patch: operations["PATCH__api_v1_admin_bid-packs_{id}"];
    trace?: never;
  };
  "/api/v1/admin/users/{id}/grant_admin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Grant admin role to a user */
    post: operations["POST__api_v1_admin_users_{id}_grant_admin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{id}/revoke_admin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke admin role from a user */
    post: operations["POST__api_v1_admin_users_{id}_revoke_admin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{id}/grant_superadmin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Grant superadmin role to a user */
    post: operations["POST__api_v1_admin_users_{id}_grant_superadmin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{id}/revoke_superadmin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke superadmin role from a user */
    post: operations["POST__api_v1_admin_users_{id}_revoke_superadmin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{id}/ban": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ban a user account */
    post: operations["POST__api_v1_admin_users_{id}_ban"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List admin and superadmin users
     * @description GET /api/v1/admin/users
     */
    get: operations["GET__api_v1_admin_users"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update an admin/superadmin user record
     * @description PATCH/PUT /api/v1/admin/users/:id
     */
    put: operations["PUT__api_v1_admin_users_{id}"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update an admin/superadmin user record
     * @description PATCH/PUT /api/v1/admin/users/:id
     */
    patch: operations["PATCH__api_v1_admin_users_{id}"];
    trace?: never;
  };
  "/api/v1/admin/payments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List payments with optional email search
     * @description GET /api/v1/admin/payments
     */
    get: operations["GET__api_v1_admin_payments"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create an audit log entry
     * @description POST /api/v1/admin/audit
     */
    post: operations["POST__api_v1_admin_audit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    d79407304a1f91dbdcfa03f0d06dc75e: {
      status: number;
      error?: string;
    };
  };
  responses: {
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    fc696adf063a01fea86e28dd537df45f: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    dd45de4d03156139b0b5d67d3ac2caf1: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    f62cfa76a264b0b883ad73045fde4c36: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    bc8ac622ba39588246b29784533dde3c: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    f089f1d3021546aaaa03173c3df2e947: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    a10845c8836e088371c8a8147d5dd395: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "8099b80a6facf25e92439f4769142b4a": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    c28671294d809e8d407c08177f3c4928: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    a38845958a657f1a34193686d8579cca: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    bc20b3bd450859d26f841961ca25553a: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "5960932ecc07ee3922d27487fe870215": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    ac23bc219c3df4c8d947a42310ddfcfc: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "13e49a27788708e63c4dc0ecfb396378": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    c680794bb8200c71656ed297228cf957: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "1e1261429aa483841cfdd3a0e4133b07": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "122945af211854f64c598f63f8728925": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    ab141042252cc27dbdf61200a1ec392e: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    c1b0b5ea30b2379849997a23f429b966: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    c8c2f7080c77184b1efed023cf92d00d: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    "174897cae4896bfcc276741edeeda3b8": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "14a3e1fdafafefdbf16b1042adcead20": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "6ced71d4721109a83a4fadecff4a3c7b": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "21714d7a21857643b8ec113759898449": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    c98dd9446cae2af9afd8384fc7c4b8c4: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    "97bd970777015230d71e61ae2f62dc8f": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "235372cfdcee1b688cede6e26713c349": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    d99af71928a59bccbce3c975b7cf0fcc: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    f382f7d4ef7dcd6392e411e059d1b43b: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    "9b468a96d2ecfbbb2f01ddbfa0c4b712": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    ba5b5133d0927f4047f3acdaa9e71f18: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "5ea1765c94df9da45ed1ee810d9fa556": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "55b8e27f34497dda73f5e0bd0a8de6ca": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "9fd2c40a06ffaa4abdfb21c88d205f00": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    "06baeeaf809ebf290e3892f4ca6789b2": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    b1064dcca37ece82445aa19a302be099: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    df6a0e787ce3509ff58d99854582f49e: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "77253ac4440631daaec0af7d5f63887f": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "534bf5181c9a4d37e601551ef5b5f65c": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    "332a84c1c89c1da003c0cddbd98f1562": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "9818c3668bfbad20629ad8ba2c8dfc79": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "5319c6fe4fe6eaca80746b59d0456790": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "6c432fd41fe8ceb5fa7c2ab0ac41d675": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "7bb4ae25d7b156d06adcdc1a30b90797": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "5749007aa68810a0b3e0eda905bd9d57": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    dde5477a9dc86ff38d4288a4d1b616a0: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    "6bd6c01642e400d8701835a28f8f1cc9": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    "3bd697afe55b0760265f2a35f57516d7": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    d8dc1c18d847130dcdc6c44235ba7e70: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    a31a9ca5fa81f9b4285b93977b822842: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    a43ea7ac1e7bc61c6b4290f650fa7215: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    da7c29882b7cfb2b114e3e7a7cdcbcfe: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "9b98a906b0ea51766c867832e5e19a97": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "59039d823203893fe02baebef2a4040f": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    "4cb3c3ad47a35f9c911ae5394416affb": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "57de5bfd75a238c39742ecbd0e9c6476": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "4139978180736a8653359b3f14d7d8eb": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "5ccd3e97340ab6fc36edc10c25f7fbb5": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    c2aa0a47b26366b360b97d5f30a41def: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "290feb945755e590fca7aff91c16a5ed": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    bf10baafccc6fff1e7d60a8b3b6c7721: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "02cd934a242054027acbce64d92c2dfa": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    c003ff4901f637260f31b64552f42f8c: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    a3384c62f3d022c8311d7753db9790fe: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    df164b9fdf17a3e60b7834f39e64668a: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    "2d68a131f131f41d17558b20076845ea": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "2f1c896ed4670985e7db1fc62458e0cc": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "14cf6747d830fe2807aa5aebcac3b87d": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "949f0d10065c6401c2e072a13bbe4ffa": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    e4e4d0249fb2450fffd298bca0d33d92: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    b5f3b8ad11cb77a952aab30a76d82930: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "2da5f3b03c5d8e256027c7f879a869c9": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    ced28128bdda79119b89b486ef4a9d9e: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    b50610372f17eb7215c38a28d9025617: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "52d44f6778ca982c359ac5a07856b46c": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "3f6a7ab0a91474a20a08ea5fd2ab4aff": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    "4cf184cb462e88678280fca46196a9d8": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "0645b3dbdec90eec7b2b42af4634751b": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    dc6ac1d8a1c448bbd8167a6a45035eb5: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    c6b8790b51fedb87d1b9c13d4ad06653: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    d702585d7accae3492fc0e177ad8eef7: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    b4cb29049fa2ccedcdcd6e85812ba809: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "306447c0c4a8baeefa60d12a28c3b524": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    cc527e6a2f04fca759c1c74a912a2564: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "2618d46fdb780ebb3300796cddbe068e": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    e49fbf526360a50f008c91c6357a30a2: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    e53be546b1e2182b275ffed1c665667a: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "8352e012fb743d9d6c00af8d79b0b097": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    fcd48a0f779d297dad43f1230c42b599: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    f8b5a272381afe6d1cb5737e4b8339de: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "1b4d888e1996d11df5f046a6438535d7": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "2281b62a90af5afe1305ff7042f3ba2e": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "26774b9e288e5772e9c215dc27cf3978": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    ad07e1c406d424945ac3f9c300ba0129: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "47c8bb62ca2a3af932ef8b63b38ccfb4": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "9c09f9170bcea9201150265db3e41d9a": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    d7b2c0fc98ab90c8d08668e9c2d7b9d4: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    b896347366baab3416084551e5608fb9: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "1afa6c725ec6fd4b769935859bb0f0d0": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "2883ddea2b5886ddce723713f49dac60": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "1e1f91c0e4a21a06bf59464a8dc25287": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    f9200fbf3cf8b1fb7c26fd60cee357db: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    c27d46243a4f90f69afe813e5ec5eb35: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    f9ad83af30608e3fea2f707f7586b7d9: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "09de2a2c0ae03a38afea4a35e15ce99d": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    df78b8c7581f2b70caada0e45a69b9a4: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "96a5d45ebd94d77ea0e49e8783fc780e": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "03aa63018149b2bfd8eccc60b9c96d5d": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    "87367cc76d4d16812f5ffbccba776afb": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "98c20af9b9be96a81a6678b2ebc98d1d": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "94687736b48557b130aafc8d253bf47b": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    ef57b65fd8c674aeab8224f76e338542: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    "2d214dc6aae3a09fdbf0e5497e7c59fc": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The requested resource could not be found. */
    "539dd52a22b85a45bd7d18d604bd4b03": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "1e937dfccbbb132517e216353232bbd4": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "6cb9f347e2b75863dbc9f659be265155": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    c5c30a279fb086091d28b43ad12d896b: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    ce5162ca08d07bab92dd31e480a3d9be: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    "5af5b486bed5c1e951db530a39063e6f": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "9201e185fe9f07fa91057969ca16af56": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "153dc198e8a9dc87fc527fa08d1dfe6e": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not authorized to access this resource. You need to authenticate yourself first. */
    d8f14b144641dd153836cdb6286987bc: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description You are not allowed to access this resource. You do not have the necessary permissions. */
    "1696e4462d8b569cc78a1222eb331147": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description An unexpected error occurred on the server. The server was unable to process the request. */
    "386021744bcddbb6037f02782153b5ad": {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
    /** @description The server could not process the request due to semantic errors. Please check your input and try again. */
    c6da2f20c6b73c73298f12dbfd30e792: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["d79407304a1f91dbdcfa03f0d06dc75e"];
      };
    };
  };
  parameters: {
    /** @description Id of existing auction. */
    "18bde8a858d6059a1187f38167ca01e3": string;
    /** @description Id of existing auction. */
    "98630f24a9e2ae556ba92595202094b3": string;
    /** @description Id of existing bid-pack. */
    "5986e4ea17012b11e0851072c66a6e70": string;
    /** @description Id of existing user. */
    aa5b9b7c9d2d28e819eadb29e4105b97: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  GET__: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: never;
  };
  POST__api_v1_checkouts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["fc696adf063a01fea86e28dd537df45f"];
      403: components["responses"]["dd45de4d03156139b0b5d67d3ac2caf1"];
      422: components["responses"]["bc8ac622ba39588246b29784533dde3c"];
      500: components["responses"]["f62cfa76a264b0b883ad73045fde4c36"];
    };
  };
  GET__api_v1_checkout_status: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["f089f1d3021546aaaa03173c3df2e947"];
      403: components["responses"]["a10845c8836e088371c8a8147d5dd395"];
      500: components["responses"]["8099b80a6facf25e92439f4769142b4a"];
    };
  };
  GET__api_v1_checkout_success: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["c28671294d809e8d407c08177f3c4928"];
      403: components["responses"]["a38845958a657f1a34193686d8579cca"];
      500: components["responses"]["bc20b3bd450859d26f841961ca25553a"];
    };
  };
  GET__api_v1_bid_packs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: never;
  };
  "POST__api_v1_auctions_{auction_id}_bids": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing auction. */
        auction_id: components["parameters"]["18bde8a858d6059a1187f38167ca01e3"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["5960932ecc07ee3922d27487fe870215"];
      403: components["responses"]["ac23bc219c3df4c8d947a42310ddfcfc"];
      422: components["responses"]["c680794bb8200c71656ed297228cf957"];
      500: components["responses"]["13e49a27788708e63c4dc0ecfb396378"];
    };
  };
  "GET__api_v1_auctions_{auction_id}_bid_history": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing auction. */
        auction_id: components["parameters"]["18bde8a858d6059a1187f38167ca01e3"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: never;
  };
  GET__api_v1_auctions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: never;
  };
  POST__api_v1_auctions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["1e1261429aa483841cfdd3a0e4133b07"];
      403: components["responses"]["122945af211854f64c598f63f8728925"];
      422: components["responses"]["c1b0b5ea30b2379849997a23f429b966"];
      500: components["responses"]["ab141042252cc27dbdf61200a1ec392e"];
    };
  };
  "GET__api_v1_auctions_{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing auction. */
        id: components["parameters"]["98630f24a9e2ae556ba92595202094b3"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      404: components["responses"]["c8c2f7080c77184b1efed023cf92d00d"];
    };
  };
  "PUT__api_v1_auctions_{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing auction. */
        id: components["parameters"]["98630f24a9e2ae556ba92595202094b3"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["235372cfdcee1b688cede6e26713c349"];
      403: components["responses"]["d99af71928a59bccbce3c975b7cf0fcc"];
      404: components["responses"]["97bd970777015230d71e61ae2f62dc8f"];
      422: components["responses"]["9b468a96d2ecfbbb2f01ddbfa0c4b712"];
      500: components["responses"]["f382f7d4ef7dcd6392e411e059d1b43b"];
    };
  };
  "DELETE__api_v1_auctions_{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing auction. */
        id: components["parameters"]["98630f24a9e2ae556ba92595202094b3"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["5ea1765c94df9da45ed1ee810d9fa556"];
      403: components["responses"]["55b8e27f34497dda73f5e0bd0a8de6ca"];
      404: components["responses"]["ba5b5133d0927f4047f3acdaa9e71f18"];
      500: components["responses"]["9fd2c40a06ffaa4abdfb21c88d205f00"];
    };
  };
  "PATCH__api_v1_auctions_{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing auction. */
        id: components["parameters"]["98630f24a9e2ae556ba92595202094b3"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["14a3e1fdafafefdbf16b1042adcead20"];
      403: components["responses"]["6ced71d4721109a83a4fadecff4a3c7b"];
      404: components["responses"]["174897cae4896bfcc276741edeeda3b8"];
      422: components["responses"]["c98dd9446cae2af9afd8384fc7c4b8c4"];
      500: components["responses"]["21714d7a21857643b8ec113759898449"];
    };
  };
  POST__api_v1_users: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      422: components["responses"]["06baeeaf809ebf290e3892f4ca6789b2"];
    };
  };
  POST__api_v1_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      422: components["responses"]["b1064dcca37ece82445aa19a302be099"];
    };
  };
  POST__api_v1_session_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: never;
  };
  GET__api_v1_session_remaining: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["df6a0e787ce3509ff58d99854582f49e"];
      403: components["responses"]["77253ac4440631daaec0af7d5f63887f"];
      500: components["responses"]["534bf5181c9a4d37e601551ef5b5f65c"];
    };
  };
  DELETE__api_v1_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["9818c3668bfbad20629ad8ba2c8dfc79"];
      403: components["responses"]["5319c6fe4fe6eaca80746b59d0456790"];
      404: components["responses"]["332a84c1c89c1da003c0cddbd98f1562"];
      500: components["responses"]["6c432fd41fe8ceb5fa7c2ab0ac41d675"];
    };
  };
  GET__api_v1_logged_in: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["7bb4ae25d7b156d06adcdc1a30b90797"];
      403: components["responses"]["5749007aa68810a0b3e0eda905bd9d57"];
      500: components["responses"]["dde5477a9dc86ff38d4288a4d1b616a0"];
    };
  };
  POST__api_v1_password_forgot: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      422: components["responses"]["6bd6c01642e400d8701835a28f8f1cc9"];
    };
  };
  POST__api_v1_password_reset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      404: components["responses"]["3bd697afe55b0760265f2a35f57516d7"];
      422: components["responses"]["d8dc1c18d847130dcdc6c44235ba7e70"];
    };
  };
  GET__api_v1_maintenance: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      404: components["responses"]["a31a9ca5fa81f9b4285b93977b822842"];
    };
  };
  GET__api_v1_admin_maintenance: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["da7c29882b7cfb2b114e3e7a7cdcbcfe"];
      403: components["responses"]["9b98a906b0ea51766c867832e5e19a97"];
      404: components["responses"]["a43ea7ac1e7bc61c6b4290f650fa7215"];
      500: components["responses"]["59039d823203893fe02baebef2a4040f"];
    };
  };
  POST__api_v1_admin_maintenance: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["57de5bfd75a238c39742ecbd0e9c6476"];
      403: components["responses"]["4139978180736a8653359b3f14d7d8eb"];
      404: components["responses"]["4cb3c3ad47a35f9c911ae5394416affb"];
      422: components["responses"]["c2aa0a47b26366b360b97d5f30a41def"];
      500: components["responses"]["5ccd3e97340ab6fc36edc10c25f7fbb5"];
    };
  };
  "GET__api_v1_admin_bid-packs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["290feb945755e590fca7aff91c16a5ed"];
      403: components["responses"]["bf10baafccc6fff1e7d60a8b3b6c7721"];
      500: components["responses"]["02cd934a242054027acbce64d92c2dfa"];
    };
  };
  "POST__api_v1_admin_bid-packs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["c003ff4901f637260f31b64552f42f8c"];
      403: components["responses"]["a3384c62f3d022c8311d7753db9790fe"];
      422: components["responses"]["2d68a131f131f41d17558b20076845ea"];
      500: components["responses"]["df164b9fdf17a3e60b7834f39e64668a"];
    };
  };
  "GET__api_v1_admin_bid-packs_new": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["2f1c896ed4670985e7db1fc62458e0cc"];
      403: components["responses"]["14cf6747d830fe2807aa5aebcac3b87d"];
      500: components["responses"]["949f0d10065c6401c2e072a13bbe4ffa"];
    };
  };
  "GET__api_v1_admin_bid-packs_{id}_edit": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing bid-pack. */
        id: components["parameters"]["5986e4ea17012b11e0851072c66a6e70"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["e4e4d0249fb2450fffd298bca0d33d92"];
      403: components["responses"]["b5f3b8ad11cb77a952aab30a76d82930"];
      500: components["responses"]["2da5f3b03c5d8e256027c7f879a869c9"];
    };
  };
  "GET__api_v1_admin_bid-packs_{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing bid-pack. */
        id: components["parameters"]["5986e4ea17012b11e0851072c66a6e70"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["b50610372f17eb7215c38a28d9025617"];
      403: components["responses"]["52d44f6778ca982c359ac5a07856b46c"];
      404: components["responses"]["ced28128bdda79119b89b486ef4a9d9e"];
      500: components["responses"]["3f6a7ab0a91474a20a08ea5fd2ab4aff"];
    };
  };
  "PUT__api_v1_admin_bid-packs_{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing bid-pack. */
        id: components["parameters"]["5986e4ea17012b11e0851072c66a6e70"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["306447c0c4a8baeefa60d12a28c3b524"];
      403: components["responses"]["cc527e6a2f04fca759c1c74a912a2564"];
      404: components["responses"]["b4cb29049fa2ccedcdcd6e85812ba809"];
      422: components["responses"]["e49fbf526360a50f008c91c6357a30a2"];
      500: components["responses"]["2618d46fdb780ebb3300796cddbe068e"];
    };
  };
  "DELETE__api_v1_admin_bid-packs_{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing bid-pack. */
        id: components["parameters"]["5986e4ea17012b11e0851072c66a6e70"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["8352e012fb743d9d6c00af8d79b0b097"];
      403: components["responses"]["fcd48a0f779d297dad43f1230c42b599"];
      404: components["responses"]["e53be546b1e2182b275ffed1c665667a"];
      500: components["responses"]["f8b5a272381afe6d1cb5737e4b8339de"];
    };
  };
  "PATCH__api_v1_admin_bid-packs_{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing bid-pack. */
        id: components["parameters"]["5986e4ea17012b11e0851072c66a6e70"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["0645b3dbdec90eec7b2b42af4634751b"];
      403: components["responses"]["dc6ac1d8a1c448bbd8167a6a45035eb5"];
      404: components["responses"]["4cf184cb462e88678280fca46196a9d8"];
      422: components["responses"]["d702585d7accae3492fc0e177ad8eef7"];
      500: components["responses"]["c6b8790b51fedb87d1b9c13d4ad06653"];
    };
  };
  "POST__api_v1_admin_users_{id}_grant_admin": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing user. */
        id: components["parameters"]["aa5b9b7c9d2d28e819eadb29e4105b97"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["1b4d888e1996d11df5f046a6438535d7"];
      403: components["responses"]["2281b62a90af5afe1305ff7042f3ba2e"];
      500: components["responses"]["26774b9e288e5772e9c215dc27cf3978"];
    };
  };
  "POST__api_v1_admin_users_{id}_revoke_admin": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing user. */
        id: components["parameters"]["aa5b9b7c9d2d28e819eadb29e4105b97"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["ad07e1c406d424945ac3f9c300ba0129"];
      403: components["responses"]["47c8bb62ca2a3af932ef8b63b38ccfb4"];
      500: components["responses"]["9c09f9170bcea9201150265db3e41d9a"];
    };
  };
  "POST__api_v1_admin_users_{id}_grant_superadmin": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing user. */
        id: components["parameters"]["aa5b9b7c9d2d28e819eadb29e4105b97"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["d7b2c0fc98ab90c8d08668e9c2d7b9d4"];
      403: components["responses"]["b896347366baab3416084551e5608fb9"];
      500: components["responses"]["1afa6c725ec6fd4b769935859bb0f0d0"];
    };
  };
  "POST__api_v1_admin_users_{id}_revoke_superadmin": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing user. */
        id: components["parameters"]["aa5b9b7c9d2d28e819eadb29e4105b97"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["2883ddea2b5886ddce723713f49dac60"];
      403: components["responses"]["1e1f91c0e4a21a06bf59464a8dc25287"];
      500: components["responses"]["f9200fbf3cf8b1fb7c26fd60cee357db"];
    };
  };
  "POST__api_v1_admin_users_{id}_ban": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing user. */
        id: components["parameters"]["aa5b9b7c9d2d28e819eadb29e4105b97"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["c27d46243a4f90f69afe813e5ec5eb35"];
      403: components["responses"]["f9ad83af30608e3fea2f707f7586b7d9"];
      500: components["responses"]["09de2a2c0ae03a38afea4a35e15ce99d"];
    };
  };
  GET__api_v1_admin_users: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["df78b8c7581f2b70caada0e45a69b9a4"];
      403: components["responses"]["96a5d45ebd94d77ea0e49e8783fc780e"];
      500: components["responses"]["03aa63018149b2bfd8eccc60b9c96d5d"];
    };
  };
  "PUT__api_v1_admin_users_{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing user. */
        id: components["parameters"]["aa5b9b7c9d2d28e819eadb29e4105b97"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["1e937dfccbbb132517e216353232bbd4"];
      403: components["responses"]["6cb9f347e2b75863dbc9f659be265155"];
      404: components["responses"]["539dd52a22b85a45bd7d18d604bd4b03"];
      422: components["responses"]["ce5162ca08d07bab92dd31e480a3d9be"];
      500: components["responses"]["c5c30a279fb086091d28b43ad12d896b"];
    };
  };
  "PATCH__api_v1_admin_users_{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of existing user. */
        id: components["parameters"]["aa5b9b7c9d2d28e819eadb29e4105b97"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["98c20af9b9be96a81a6678b2ebc98d1d"];
      403: components["responses"]["94687736b48557b130aafc8d253bf47b"];
      404: components["responses"]["87367cc76d4d16812f5ffbccba776afb"];
      422: components["responses"]["2d214dc6aae3a09fdbf0e5497e7c59fc"];
      500: components["responses"]["ef57b65fd8c674aeab8224f76e338542"];
    };
  };
  GET__api_v1_admin_payments: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["5af5b486bed5c1e951db530a39063e6f"];
      403: components["responses"]["9201e185fe9f07fa91057969ca16af56"];
      500: components["responses"]["153dc198e8a9dc87fc527fa08d1dfe6e"];
    };
  };
  POST__api_v1_admin_audit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      401: components["responses"]["d8f14b144641dd153836cdb6286987bc"];
      403: components["responses"]["1696e4462d8b569cc78a1222eb331147"];
      422: components["responses"]["c6da2f20c6b73c73298f12dbfd30e792"];
      500: components["responses"]["386021744bcddbb6037f02782153b5ad"];
    };
  };
}
